### ISSUE TITLE
module cannot be imported after install

### ISSUE THREAD

**Issue by izloop** [RobertDresler/CalendarFoundation#2]
I am not able to add the module to my xcworkspace file after installing the CalendarFoundation pod in the appropriate project.

Below is a screenshots.

<img width="814" alt="Screen Shot 2019-05-31 at 2 40 07 AM" src="https://user-images.githubusercontent.com/38543275/58673928-d3c2f300-834d-11e9-8b77-a35de2985403.png">

**Comment by arnavvaryani** [comment]
I had the same error, try to reinstall the cocoapod and update it. After that compile your Xcode project and then you can import it in your file.

**Comment by RobertDresler** [comment]
Solved in email thread:

Hi, 

and thank you that you’ve decided to use my framework. This error can be caused by lot of things and I don’t think that it is a problem of framework itself.

Make sure that you’ve installed pod (`pod install`) or try to update it using `pod update`. Also make sure that you open **xcworkspace** (project with white icon generated after pod install). 

If any of this doesn’t work, contact me again and tell me which version of Swift you use and what is deployment target for your project.

Best regards,
Robert Dresler 😊

**Comment by izloop** [comment]
Hey, 

Thanks - yeah I installed it correctly and opened the correct file as well! 
Sadly none of this worked! :/ 

I am using Swift 5. and the Deployment Target is 12.2.

Thanks in advance,
IPL

**Comment by izloop** [comment]
Hey @RobertDresler,

Thanks - yeah I installed it correctly and opened the correct file as well!
Sadly none of this worked! :/

I am using Swift 5. and the Deployment Target is 12.2.

Thanks in advance,
IPL

**Comment by RobertDresler** [comment]
@izloop can you try to deintegrate pods and install them again? 

1. `pod deintegrate`
2. `pod install`
3. `pod update` (optional)
